services:
  traefik:
    command:
      # - "--log.level=DEBUG"
      # - "--accesslog=true"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls.options=default@file"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.file.filename=/config/tls-config.yaml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ui.entrypoints=websecure"
      - "traefik.http.routers.traefik-ui.tls=true"
      - "traefik.http.routers.traefik-ui.rule=Host(`traefik.${SERVER_NAME}`)"
      - "traefik.http.routers.traefik-ui.service=api@internal"
      - "traefik.http.routers.traefik-ui.middlewares=traefik-auth, security-headers"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH}"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./config/traefik/tls-config.yaml:/config/tls-config.yaml
      - ./secrets/traefik/certificate.pem:/secrets/certificate.pem:ro
      - ./secrets/traefik/privkey.pem:/secrets/privkey.pem:ro

  prometheus:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${SERVER_NAME}`)"
      - "traefik.http.routers.prometheus.middlewares=traefik-auth, security-headers"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=app-net"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${SERVER_NAME}`)"
      - "traefik.http.routers.grafana.middlewares=traefik-auth, security-headers"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=app-net"
