services:
  traefik:
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.traefik.address=:8080"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ui.entrypoints=web, traefik"
      - "traefik.http.routers.traefik-ui.rule=Host(`traefik.${SERVER_NAME}`)"
      - "traefik.http.routers.traefik-ui.service=api@internal"
    ports:
      - "${TRAEFIK_PORT}:8080"  # dashboard

  prometheus:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=web, traefik"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${SERVER_NAME}`)"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=app-net"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web, traefik"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${SERVER_NAME}`)"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=app-net"
