x-env-logging: &env-logging
  options:
    max-size: "10m"
    max-file: "3"

services:
  traefik:
    image: traefik:2.10
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-network
      - application-network

  maintenance-page:
    image: nginx:stable
    restart: always
    volumes:
      - ./config/maintenance-page/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./config/maintenance-page/maintenance.html:/usr/share/nginx/html/maintenance.html:ro
    networks:
      - application-network

  prometheus:
    image: prom/prometheus:v2.43.0
    restart: always
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_vol:/prometheus
    networks:
      - application-network
    logging:
      <<: *env-logging

  grafana:
    image: grafana/grafana:9.5.1
    depends_on:
      - prometheus
    restart: always
    env_file:
      - ./config/grafana/config.monitoring
    volumes:
      - grafana_vol:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - application-network
    logging:
      <<: *env-logging

volumes:
  prometheus_vol:
  grafana_vol:

networks:
  application-network:
    name: app-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: $DOCKER_DAEMON_MTU
  traefik-network:
    name: traefik-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: $DOCKER_DAEMON_MTU
